name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b96322cb847462f1e21f0510cd5d543066db1d81827572e72bdf48f15cdb5626"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
