name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66ccf323d7f53d1d28971fa82fc74d4e76659acd086ededcbaf924f0e3ef33ea"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
