name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9e35b0278546f7c937b2558ec0795be94f5551b53ff92ef88f374af037a03d1"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
