name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdc51f428238f0f75b68a32ae70b1c013cdd1ee18837a2a125f045051305580a"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
