name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ebed52ad19ffbd1fde6381e3efac4040c64dd56ad7934f8c84aa083d000e98b"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
