name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "317c5e7e2101f0a1a6386a8bf21b6b3697576265aa7469b4ee30e719023ce053"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
