name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6895ccff5b49de22fac264b6ae90e78bca4811db92d9afbab94215297f42dfd"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
