name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7f1ba84eca3b5b7e2c4b96447dc1be09503875c22a709ca7a5bb154713222a7"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
