name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23f8905fcf52e8ebc36a411c7e7bd85e926b2b369e590fc757826ebad86c4913"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
