name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d53f817646f79813792e915c49ac766a5a5b88d7f478cbab3a3c84adfd7398c5"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
