name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95aed9d33c69bf494e5cc802fc292be2f1fb29a7a9c00ac612b05e357d250edd"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
