name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9d953eadd34c3892fcc9e8f629639412544e8f134e8facf94cc54b8306d56db"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
