name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "142bd69ee87232f3c7e13c4947c674e605a02d802105c55d65af67c181154e18"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
