name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1931828fbdf3ec62b36700ff68eefe245ec3f6820dc525348078304920ee05b"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
