name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0baeeff15054ee6a143e0dcfb49e038580122d1391cd625deb685f8ddcf8452"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
