name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89c37c079d77b921ac573e2d6e9412c285bbd213a881278be44536f42777df99"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
