name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e32b1179ccc5cef8191177d10832f02e1250674cfc92f259028c40f0510804f"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
