name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d683ad7b86947b4dc3b0ab953042b59b04d08ae046f14277c9da772dea28ec9e"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
