name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a10b8e00a0e181b348dc00e13df6678803af601eb06212eb188ec1ce16d34271"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
