name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faa3256ee8b9e3aabdf05e28aab6c11ae7872cd982f8f09153920ce9398019d6"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
