name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaf3fdad639dc98a23d8acec3d7b9a23cb5d8093a491545328de05f4f6a28438"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
