name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52ec247c6a1a94923077427ad386b295bb52d5ce49168ff6378fa34969ba2fc7"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
