name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79157cc06912c3c804cff29490b6a3f1bd546ed52ca82b3261a1d4bd1b303184"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
