name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64bb3e8b5564b54d4b6cc2bc96fe95a3614f5ca3b8e1511b5e96f01785a5c143"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
