name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61ed38d909db98179d8bb59effee90f29ff3a7869975a56573b633391f5c13ec"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
