name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf7e717c5d1fc9db08228c0e32ef10f8c0a354e0156a2d0a9b3d15b88b1dae9e"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
