name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6417d9b107004d2b63e489fcd72e981b54084ab107d5eb974b785477054c3ce6"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
