name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96e301148c5b37dfafa9b3e453fa69063d69a85ba324103a579f9613e1c52136"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
