name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a2319a6fe1232bd24c7494871a9008b6122c80d87427c66dd0a4822c21e60ed"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
