name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "666df4c32f5f3fe427747a4ee97511c6706d1d2283b608e9342de3eaf3ca278f"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
