name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "708213a1131051a556b94773fa330acf822cdbe18059bf0ebc390e6c443750c0"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
