name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af19aab14ecaf5de4bf54e92adf7cff4632101127c67840e56f62cf16e42ec79"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
