name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c0d5165e0524175d824fced4a22efe7b2f814a3211f0bc7f01d489b7847dfe6"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
