name = "Spooky Pack 24"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41e265725d2ac55bfeb3557c389df09e86a9a676fdfc3a6885024a89d5331607"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
